name: Reusable Workflow Caller

on:
  push:

jobs:
  Reusable-caller-job:
    uses: ./.github/workflows/maven-cache.yml
    secrets:
      DH_USERNAME: ${{ secrets.DH_USERNAME }}
      DH_TOKEN: ${{ secrets.DH_TOKEN }}
