name: Reusable Workflow Caller

on:
  push:

jobs:
  Reusable-caller-job:
    uses: ./.github/workflows/maven-cache.yml
    secrets:
      DH_USERNAME: ${{ DH_USERNAME }}
      DH_TOKEN: ${{ DH_TOKEN }}
